// Code generated by goctl. DO NOT EDIT.
package types

type UploadImgRequest struct {
	Hash      string `json:"hash,optional"`
	Name      string `json:"name,optional"`
	Ext       string `json:"ext,optional"`
	Size      int64  `json:"size,optional"`
	ShortName string `json:"shortname,optional"`
}

type UploadImgResponse struct {
	DownloadURL string `json:"downloadurl"`
	ShortURL    string `json:"shorturl"`
}

type RedirectShortURLRequest struct {
	ShortName string `path:"shortname"`
}

type RedirectShortURLResponse struct {
}

type IndexRequest struct {
}

type IndexResponse struct {
}
