// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/imgbjs/imgbjs/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: Game2048Handler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/index",
				Handler: IndexHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/uploadimg",
				Handler: UploadImgHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/a/:shortname",
				Handler: RedirectShortURLHandler(serverCtx),
			},
		},
	)
}
